name: Deploy
on:
  push:
    tags:
      - '*'
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.5
      - run: npm ci
      # TODO add build, test, deploy commands
